name: "Call Composite Action"

on: [workflow_dispatch]

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/composite-action
